<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_Verbruikmeter" Id="{252b6bc1-8187-4ce6-bfbc-b81f549e6914}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Verbruikmeter
VAR
	Meetsignaal	: Verbruik_input;
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>