<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_Stopcontact" Id="{4f4e8c13-b316-4d55-9d9a-01d11f7ddfdd}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Stopcontact
VAR
	Output			: Stopcontact_output;
	kWh_meter		: FB_Verbruikmeter;
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>